### ISSUE TITLE
Implement the coverage pool balance in dashboard per the reference design

### ISSUE THREAD

**Issue by erdogan** [threshold-network/website#88]
```[tasklist]
### Tasks
- [ ] https://github.com/threshold-network/token-dashboard/pull/613
- [ ] https://github.com/threshold-network/token-dashboard/pull/614
- [ ] https://github.com/threshold-network/token-dashboard/pull/620
```

**Comment by erdogan** [comment]
Ref design: 
https://github.com/threshold-network/token-dashboard/issues/530

cc @michalsmiarowski @r-czajkowski
